name: run_tests
on: [push]
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install spim
        run: sudo apt-get install spim

      - name: Run tests
        run: ./scripts/run_tests.sh
